# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0c78ed2e7e26c67f5a7e810f57b76cc4e9e17174b56193eb6711163c616f25ff4ea126a921597ca226a0d61dac376a9c0ff7f4c1ef1e01cdb1d616d09434a3ed

test:
  secret_key_base: 51e3c3a09416adac83a4b7a19292cbcd5d90265fcff3a2ccd9aaf9b1ccee3b6bd437447d5cae9c737e3bb204a01f82df7e4ea4f597acf523ad2b6187d9f7c21f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
